# Generated by Django 3.2.5 on 2021-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210716_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_silkroad',
            name='username',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
    ]
