# Generated by Django 3.2.5 on 2021-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='region',
            field=models.CharField(blank=True, choices=[('0', 'Чуй'), ('1', 'Ош'), ('2', 'Иссык - Куль')], max_length=50, null=True),
        ),
    ]
