# Generated by Django 3.2.5 on 2021-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_content_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='region',
            field=models.CharField(blank=True, choices=[('0', 'Чуй'), ('1', 'Ош'), ('2', 'Иссык - Куль'), ('3', 'Баткен'), ('4', 'Джалал - Абад'), ('5', 'Нарын')], max_length=50, null=True),
        ),
    ]
